// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders.proto

package investapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Направление операции
type OrderDirection int32

const (
	OrderDirection_ORDER_DIRECTION_UNSPECIFIED OrderDirection = 0
	OrderDirection_ORDER_DIRECTION_BUY         OrderDirection = 1
	OrderDirection_ORDER_DIRECTION_SELL        OrderDirection = 2
)

var OrderDirection_name = map[int32]string{
	0: "ORDER_DIRECTION_UNSPECIFIED",
	1: "ORDER_DIRECTION_BUY",
	2: "ORDER_DIRECTION_SELL",
}

var OrderDirection_value = map[string]int32{
	"ORDER_DIRECTION_UNSPECIFIED": 0,
	"ORDER_DIRECTION_BUY":         1,
	"ORDER_DIRECTION_SELL":        2,
}

func (x OrderDirection) String() string {
	return proto.EnumName(OrderDirection_name, int32(x))
}

func (OrderDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0}
}

//Тип заявки
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "ORDER_TYPE_UNSPECIFIED",
	1: "ORDER_TYPE_LIMIT",
	2: "ORDER_TYPE_MARKET",
}

var OrderType_value = map[string]int32{
	"ORDER_TYPE_UNSPECIFIED": 0,
	"ORDER_TYPE_LIMIT":       1,
	"ORDER_TYPE_MARKET":      2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{1}
}

//Текущий статус заявки (поручения)
type OrderExecutionReportStatus int32

const (
	OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_UNSPECIFIED   OrderExecutionReportStatus = 0
	OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_FILL          OrderExecutionReportStatus = 1
	OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_REJECTED      OrderExecutionReportStatus = 2
	OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_CANCELLED     OrderExecutionReportStatus = 3
	OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_NEW           OrderExecutionReportStatus = 4
	OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_PARTIALLYFILL OrderExecutionReportStatus = 5
)

var OrderExecutionReportStatus_name = map[int32]string{
	0: "EXECUTION_REPORT_STATUS_UNSPECIFIED",
	1: "EXECUTION_REPORT_STATUS_FILL",
	2: "EXECUTION_REPORT_STATUS_REJECTED",
	3: "EXECUTION_REPORT_STATUS_CANCELLED",
	4: "EXECUTION_REPORT_STATUS_NEW",
	5: "EXECUTION_REPORT_STATUS_PARTIALLYFILL",
}

var OrderExecutionReportStatus_value = map[string]int32{
	"EXECUTION_REPORT_STATUS_UNSPECIFIED":   0,
	"EXECUTION_REPORT_STATUS_FILL":          1,
	"EXECUTION_REPORT_STATUS_REJECTED":      2,
	"EXECUTION_REPORT_STATUS_CANCELLED":     3,
	"EXECUTION_REPORT_STATUS_NEW":           4,
	"EXECUTION_REPORT_STATUS_PARTIALLYFILL": 5,
}

func (x OrderExecutionReportStatus) String() string {
	return proto.EnumName(OrderExecutionReportStatus_name, int32(x))
}

func (OrderExecutionReportStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{2}
}

//Запрос установки соединения.
type TradesStreamRequest struct {
	Accounts             []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradesStreamRequest) Reset()         { *m = TradesStreamRequest{} }
func (m *TradesStreamRequest) String() string { return proto.CompactTextString(m) }
func (*TradesStreamRequest) ProtoMessage()    {}
func (*TradesStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{0}
}

func (m *TradesStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradesStreamRequest.Unmarshal(m, b)
}
func (m *TradesStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradesStreamRequest.Marshal(b, m, deterministic)
}
func (m *TradesStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradesStreamRequest.Merge(m, src)
}
func (m *TradesStreamRequest) XXX_Size() int {
	return xxx_messageInfo_TradesStreamRequest.Size(m)
}
func (m *TradesStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TradesStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TradesStreamRequest proto.InternalMessageInfo

func (m *TradesStreamRequest) GetAccounts() []string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

//Информация о торговых поручениях.
type TradesStreamResponse struct {
	// Types that are valid to be assigned to Payload:
	//	*TradesStreamResponse_OrderTrades
	//	*TradesStreamResponse_Ping
	Payload              isTradesStreamResponse_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TradesStreamResponse) Reset()         { *m = TradesStreamResponse{} }
func (m *TradesStreamResponse) String() string { return proto.CompactTextString(m) }
func (*TradesStreamResponse) ProtoMessage()    {}
func (*TradesStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{1}
}

func (m *TradesStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradesStreamResponse.Unmarshal(m, b)
}
func (m *TradesStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradesStreamResponse.Marshal(b, m, deterministic)
}
func (m *TradesStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradesStreamResponse.Merge(m, src)
}
func (m *TradesStreamResponse) XXX_Size() int {
	return xxx_messageInfo_TradesStreamResponse.Size(m)
}
func (m *TradesStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TradesStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TradesStreamResponse proto.InternalMessageInfo

type isTradesStreamResponse_Payload interface {
	isTradesStreamResponse_Payload()
}

type TradesStreamResponse_OrderTrades struct {
	OrderTrades *OrderTrades `protobuf:"bytes,1,opt,name=order_trades,json=orderTrades,proto3,oneof"`
}

type TradesStreamResponse_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*TradesStreamResponse_OrderTrades) isTradesStreamResponse_Payload() {}

func (*TradesStreamResponse_Ping) isTradesStreamResponse_Payload() {}

func (m *TradesStreamResponse) GetPayload() isTradesStreamResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TradesStreamResponse) GetOrderTrades() *OrderTrades {
	if x, ok := m.GetPayload().(*TradesStreamResponse_OrderTrades); ok {
		return x.OrderTrades
	}
	return nil
}

func (m *TradesStreamResponse) GetPing() *Ping {
	if x, ok := m.GetPayload().(*TradesStreamResponse_Ping); ok {
		return x.Ping
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TradesStreamResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TradesStreamResponse_OrderTrades)(nil),
		(*TradesStreamResponse_Ping)(nil),
	}
}

//Информация об исполнении торгового поручения.
type OrderTrades struct {
	OrderId              string               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Direction            OrderDirection       `protobuf:"varint,3,opt,name=direction,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderDirection" json:"direction,omitempty"`
	Figi                 string               `protobuf:"bytes,4,opt,name=figi,proto3" json:"figi,omitempty"`
	Trades               []*OrderTrade        `protobuf:"bytes,5,rep,name=trades,proto3" json:"trades,omitempty"`
	AccountId            string               `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderTrades) Reset()         { *m = OrderTrades{} }
func (m *OrderTrades) String() string { return proto.CompactTextString(m) }
func (*OrderTrades) ProtoMessage()    {}
func (*OrderTrades) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{2}
}

func (m *OrderTrades) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderTrades.Unmarshal(m, b)
}
func (m *OrderTrades) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderTrades.Marshal(b, m, deterministic)
}
func (m *OrderTrades) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderTrades.Merge(m, src)
}
func (m *OrderTrades) XXX_Size() int {
	return xxx_messageInfo_OrderTrades.Size(m)
}
func (m *OrderTrades) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderTrades.DiscardUnknown(m)
}

var xxx_messageInfo_OrderTrades proto.InternalMessageInfo

func (m *OrderTrades) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderTrades) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *OrderTrades) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ORDER_DIRECTION_UNSPECIFIED
}

func (m *OrderTrades) GetFigi() string {
	if m != nil {
		return m.Figi
	}
	return ""
}

func (m *OrderTrades) GetTrades() []*OrderTrade {
	if m != nil {
		return m.Trades
	}
	return nil
}

func (m *OrderTrades) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//Информация о сделке.
type OrderTrade struct {
	DateTime             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Price                *Quotation           `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64                `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderTrade) Reset()         { *m = OrderTrade{} }
func (m *OrderTrade) String() string { return proto.CompactTextString(m) }
func (*OrderTrade) ProtoMessage()    {}
func (*OrderTrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{3}
}

func (m *OrderTrade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderTrade.Unmarshal(m, b)
}
func (m *OrderTrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderTrade.Marshal(b, m, deterministic)
}
func (m *OrderTrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderTrade.Merge(m, src)
}
func (m *OrderTrade) XXX_Size() int {
	return xxx_messageInfo_OrderTrade.Size(m)
}
func (m *OrderTrade) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderTrade.DiscardUnknown(m)
}

var xxx_messageInfo_OrderTrade proto.InternalMessageInfo

func (m *OrderTrade) GetDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DateTime
	}
	return nil
}

func (m *OrderTrade) GetPrice() *Quotation {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *OrderTrade) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

//Запрос выставления торгового поручения.
type PostOrderRequest struct {
	Figi                 string         `protobuf:"bytes,1,opt,name=figi,proto3" json:"figi,omitempty"`
	Quantity             int64          `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                *Quotation     `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Direction            OrderDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderDirection" json:"direction,omitempty"`
	AccountId            string         `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrderType            OrderType      `protobuf:"varint,6,opt,name=order_type,json=orderType,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderType" json:"order_type,omitempty"`
	OrderId              string         `protobuf:"bytes,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PostOrderRequest) Reset()         { *m = PostOrderRequest{} }
func (m *PostOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PostOrderRequest) ProtoMessage()    {}
func (*PostOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{4}
}

func (m *PostOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderRequest.Unmarshal(m, b)
}
func (m *PostOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderRequest.Marshal(b, m, deterministic)
}
func (m *PostOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderRequest.Merge(m, src)
}
func (m *PostOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PostOrderRequest.Size(m)
}
func (m *PostOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderRequest proto.InternalMessageInfo

func (m *PostOrderRequest) GetFigi() string {
	if m != nil {
		return m.Figi
	}
	return ""
}

func (m *PostOrderRequest) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *PostOrderRequest) GetPrice() *Quotation {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *PostOrderRequest) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ORDER_DIRECTION_UNSPECIFIED
}

func (m *PostOrderRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *PostOrderRequest) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *PostOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

//Информация о выставлении поручения.
type PostOrderResponse struct {
	OrderId               string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ExecutionReportStatus OrderExecutionReportStatus `protobuf:"varint,2,opt,name=execution_report_status,json=executionReportStatus,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderExecutionReportStatus" json:"execution_report_status,omitempty"`
	LotsRequested         int64                      `protobuf:"varint,3,opt,name=lots_requested,json=lotsRequested,proto3" json:"lots_requested,omitempty"`
	LotsExecuted          int64                      `protobuf:"varint,4,opt,name=lots_executed,json=lotsExecuted,proto3" json:"lots_executed,omitempty"`
	InitialOrderPrice     *MoneyValue                `protobuf:"bytes,5,opt,name=initial_order_price,json=initialOrderPrice,proto3" json:"initial_order_price,omitempty"`
	ExecutedOrderPrice    *MoneyValue                `protobuf:"bytes,6,opt,name=executed_order_price,json=executedOrderPrice,proto3" json:"executed_order_price,omitempty"`
	TotalOrderAmount      *MoneyValue                `protobuf:"bytes,7,opt,name=total_order_amount,json=totalOrderAmount,proto3" json:"total_order_amount,omitempty"`
	InitialCommission     *MoneyValue                `protobuf:"bytes,8,opt,name=initial_commission,json=initialCommission,proto3" json:"initial_commission,omitempty"`
	ExecutedCommission    *MoneyValue                `protobuf:"bytes,9,opt,name=executed_commission,json=executedCommission,proto3" json:"executed_commission,omitempty"`
	AciValue              *MoneyValue                `protobuf:"bytes,10,opt,name=aci_value,json=aciValue,proto3" json:"aci_value,omitempty"`
	Figi                  string                     `protobuf:"bytes,11,opt,name=figi,proto3" json:"figi,omitempty"`
	Direction             OrderDirection             `protobuf:"varint,12,opt,name=direction,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderDirection" json:"direction,omitempty"`
	InitialSecurityPrice  *MoneyValue                `protobuf:"bytes,13,opt,name=initial_security_price,json=initialSecurityPrice,proto3" json:"initial_security_price,omitempty"`
	OrderType             OrderType                  `protobuf:"varint,14,opt,name=order_type,json=orderType,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderType" json:"order_type,omitempty"`
	Message               string                     `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`
	InitialOrderPricePt   *Quotation                 `protobuf:"bytes,16,opt,name=initial_order_price_pt,json=initialOrderPricePt,proto3" json:"initial_order_price_pt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                   `json:"-"`
	XXX_unrecognized      []byte                     `json:"-"`
	XXX_sizecache         int32                      `json:"-"`
}

func (m *PostOrderResponse) Reset()         { *m = PostOrderResponse{} }
func (m *PostOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PostOrderResponse) ProtoMessage()    {}
func (*PostOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{5}
}

func (m *PostOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderResponse.Unmarshal(m, b)
}
func (m *PostOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderResponse.Marshal(b, m, deterministic)
}
func (m *PostOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderResponse.Merge(m, src)
}
func (m *PostOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PostOrderResponse.Size(m)
}
func (m *PostOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderResponse proto.InternalMessageInfo

func (m *PostOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PostOrderResponse) GetExecutionReportStatus() OrderExecutionReportStatus {
	if m != nil {
		return m.ExecutionReportStatus
	}
	return OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_UNSPECIFIED
}

func (m *PostOrderResponse) GetLotsRequested() int64 {
	if m != nil {
		return m.LotsRequested
	}
	return 0
}

func (m *PostOrderResponse) GetLotsExecuted() int64 {
	if m != nil {
		return m.LotsExecuted
	}
	return 0
}

func (m *PostOrderResponse) GetInitialOrderPrice() *MoneyValue {
	if m != nil {
		return m.InitialOrderPrice
	}
	return nil
}

func (m *PostOrderResponse) GetExecutedOrderPrice() *MoneyValue {
	if m != nil {
		return m.ExecutedOrderPrice
	}
	return nil
}

func (m *PostOrderResponse) GetTotalOrderAmount() *MoneyValue {
	if m != nil {
		return m.TotalOrderAmount
	}
	return nil
}

func (m *PostOrderResponse) GetInitialCommission() *MoneyValue {
	if m != nil {
		return m.InitialCommission
	}
	return nil
}

func (m *PostOrderResponse) GetExecutedCommission() *MoneyValue {
	if m != nil {
		return m.ExecutedCommission
	}
	return nil
}

func (m *PostOrderResponse) GetAciValue() *MoneyValue {
	if m != nil {
		return m.AciValue
	}
	return nil
}

func (m *PostOrderResponse) GetFigi() string {
	if m != nil {
		return m.Figi
	}
	return ""
}

func (m *PostOrderResponse) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ORDER_DIRECTION_UNSPECIFIED
}

func (m *PostOrderResponse) GetInitialSecurityPrice() *MoneyValue {
	if m != nil {
		return m.InitialSecurityPrice
	}
	return nil
}

func (m *PostOrderResponse) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *PostOrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PostOrderResponse) GetInitialOrderPricePt() *Quotation {
	if m != nil {
		return m.InitialOrderPricePt
	}
	return nil
}

//Запрос отмены торгового поручения.
type CancelOrderRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{6}
}

func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(m, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *CancelOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

//Результат отмены торгового поручения.
type CancelOrderResponse struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CancelOrderResponse) Reset()         { *m = CancelOrderResponse{} }
func (m *CancelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResponse) ProtoMessage()    {}
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{7}
}

func (m *CancelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResponse.Unmarshal(m, b)
}
func (m *CancelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResponse.Marshal(b, m, deterministic)
}
func (m *CancelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResponse.Merge(m, src)
}
func (m *CancelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResponse.Size(m)
}
func (m *CancelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResponse proto.InternalMessageInfo

func (m *CancelOrderResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

//Запрос получения статуса торгового поручения.
type GetOrderStateRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderStateRequest) Reset()         { *m = GetOrderStateRequest{} }
func (m *GetOrderStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderStateRequest) ProtoMessage()    {}
func (*GetOrderStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{8}
}

func (m *GetOrderStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderStateRequest.Unmarshal(m, b)
}
func (m *GetOrderStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderStateRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderStateRequest.Merge(m, src)
}
func (m *GetOrderStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderStateRequest.Size(m)
}
func (m *GetOrderStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderStateRequest proto.InternalMessageInfo

func (m *GetOrderStateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *GetOrderStateRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

//Запрос получения списка активных торговых поручений.
type GetOrdersRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersRequest) Reset()         { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()    {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{9}
}

func (m *GetOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersRequest.Unmarshal(m, b)
}
func (m *GetOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersRequest.Marshal(b, m, deterministic)
}
func (m *GetOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersRequest.Merge(m, src)
}
func (m *GetOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersRequest.Size(m)
}
func (m *GetOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersRequest proto.InternalMessageInfo

func (m *GetOrdersRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//Список активных торговых поручений.
type GetOrdersResponse struct {
	Orders               []*OrderState `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetOrdersResponse) Reset()         { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()    {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{10}
}

func (m *GetOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersResponse.Unmarshal(m, b)
}
func (m *GetOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersResponse.Merge(m, src)
}
func (m *GetOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersResponse.Size(m)
}
func (m *GetOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersResponse proto.InternalMessageInfo

func (m *GetOrdersResponse) GetOrders() []*OrderState {
	if m != nil {
		return m.Orders
	}
	return nil
}

//Информация о торговом поручении.
type OrderState struct {
	OrderId               string                     `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ExecutionReportStatus OrderExecutionReportStatus `protobuf:"varint,2,opt,name=execution_report_status,json=executionReportStatus,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderExecutionReportStatus" json:"execution_report_status,omitempty"`
	LotsRequested         int64                      `protobuf:"varint,3,opt,name=lots_requested,json=lotsRequested,proto3" json:"lots_requested,omitempty"`
	LotsExecuted          int64                      `protobuf:"varint,4,opt,name=lots_executed,json=lotsExecuted,proto3" json:"lots_executed,omitempty"`
	InitialOrderPrice     *MoneyValue                `protobuf:"bytes,5,opt,name=initial_order_price,json=initialOrderPrice,proto3" json:"initial_order_price,omitempty"`
	ExecutedOrderPrice    *MoneyValue                `protobuf:"bytes,6,opt,name=executed_order_price,json=executedOrderPrice,proto3" json:"executed_order_price,omitempty"`
	TotalOrderAmount      *MoneyValue                `protobuf:"bytes,7,opt,name=total_order_amount,json=totalOrderAmount,proto3" json:"total_order_amount,omitempty"`
	AveragePositionPrice  *MoneyValue                `protobuf:"bytes,8,opt,name=average_position_price,json=averagePositionPrice,proto3" json:"average_position_price,omitempty"`
	InitialCommission     *MoneyValue                `protobuf:"bytes,9,opt,name=initial_commission,json=initialCommission,proto3" json:"initial_commission,omitempty"`
	ExecutedCommission    *MoneyValue                `protobuf:"bytes,10,opt,name=executed_commission,json=executedCommission,proto3" json:"executed_commission,omitempty"`
	Figi                  string                     `protobuf:"bytes,11,opt,name=figi,proto3" json:"figi,omitempty"`
	Direction             OrderDirection             `protobuf:"varint,12,opt,name=direction,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderDirection" json:"direction,omitempty"`
	InitialSecurityPrice  *MoneyValue                `protobuf:"bytes,13,opt,name=initial_security_price,json=initialSecurityPrice,proto3" json:"initial_security_price,omitempty"`
	Stages                []*OrderStage              `protobuf:"bytes,14,rep,name=stages,proto3" json:"stages,omitempty"`
	ServiceCommission     *MoneyValue                `protobuf:"bytes,15,opt,name=service_commission,json=serviceCommission,proto3" json:"service_commission,omitempty"`
	Currency              string                     `protobuf:"bytes,16,opt,name=currency,proto3" json:"currency,omitempty"`
	OrderType             OrderType                  `protobuf:"varint,17,opt,name=order_type,json=orderType,proto3,enum=tinkoff.public.invest.api.contract.v1.OrderType" json:"order_type,omitempty"`
	OrderDate             *timestamp.Timestamp       `protobuf:"bytes,18,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                   `json:"-"`
	XXX_unrecognized      []byte                     `json:"-"`
	XXX_sizecache         int32                      `json:"-"`
}

func (m *OrderState) Reset()         { *m = OrderState{} }
func (m *OrderState) String() string { return proto.CompactTextString(m) }
func (*OrderState) ProtoMessage()    {}
func (*OrderState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{11}
}

func (m *OrderState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderState.Unmarshal(m, b)
}
func (m *OrderState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderState.Marshal(b, m, deterministic)
}
func (m *OrderState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderState.Merge(m, src)
}
func (m *OrderState) XXX_Size() int {
	return xxx_messageInfo_OrderState.Size(m)
}
func (m *OrderState) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderState.DiscardUnknown(m)
}

var xxx_messageInfo_OrderState proto.InternalMessageInfo

func (m *OrderState) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderState) GetExecutionReportStatus() OrderExecutionReportStatus {
	if m != nil {
		return m.ExecutionReportStatus
	}
	return OrderExecutionReportStatus_EXECUTION_REPORT_STATUS_UNSPECIFIED
}

func (m *OrderState) GetLotsRequested() int64 {
	if m != nil {
		return m.LotsRequested
	}
	return 0
}

func (m *OrderState) GetLotsExecuted() int64 {
	if m != nil {
		return m.LotsExecuted
	}
	return 0
}

func (m *OrderState) GetInitialOrderPrice() *MoneyValue {
	if m != nil {
		return m.InitialOrderPrice
	}
	return nil
}

func (m *OrderState) GetExecutedOrderPrice() *MoneyValue {
	if m != nil {
		return m.ExecutedOrderPrice
	}
	return nil
}

func (m *OrderState) GetTotalOrderAmount() *MoneyValue {
	if m != nil {
		return m.TotalOrderAmount
	}
	return nil
}

func (m *OrderState) GetAveragePositionPrice() *MoneyValue {
	if m != nil {
		return m.AveragePositionPrice
	}
	return nil
}

func (m *OrderState) GetInitialCommission() *MoneyValue {
	if m != nil {
		return m.InitialCommission
	}
	return nil
}

func (m *OrderState) GetExecutedCommission() *MoneyValue {
	if m != nil {
		return m.ExecutedCommission
	}
	return nil
}

func (m *OrderState) GetFigi() string {
	if m != nil {
		return m.Figi
	}
	return ""
}

func (m *OrderState) GetDirection() OrderDirection {
	if m != nil {
		return m.Direction
	}
	return OrderDirection_ORDER_DIRECTION_UNSPECIFIED
}

func (m *OrderState) GetInitialSecurityPrice() *MoneyValue {
	if m != nil {
		return m.InitialSecurityPrice
	}
	return nil
}

func (m *OrderState) GetStages() []*OrderStage {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *OrderState) GetServiceCommission() *MoneyValue {
	if m != nil {
		return m.ServiceCommission
	}
	return nil
}

func (m *OrderState) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *OrderState) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *OrderState) GetOrderDate() *timestamp.Timestamp {
	if m != nil {
		return m.OrderDate
	}
	return nil
}

//Сделки в рамках торгового поручения.
type OrderStage struct {
	Price                *MoneyValue `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64       `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TradeId              string      `protobuf:"bytes,3,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderStage) Reset()         { *m = OrderStage{} }
func (m *OrderStage) String() string { return proto.CompactTextString(m) }
func (*OrderStage) ProtoMessage()    {}
func (*OrderStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f5d4cf0fc9e41b, []int{12}
}

func (m *OrderStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStage.Unmarshal(m, b)
}
func (m *OrderStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStage.Marshal(b, m, deterministic)
}
func (m *OrderStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStage.Merge(m, src)
}
func (m *OrderStage) XXX_Size() int {
	return xxx_messageInfo_OrderStage.Size(m)
}
func (m *OrderStage) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStage.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStage proto.InternalMessageInfo

func (m *OrderStage) GetPrice() *MoneyValue {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *OrderStage) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderStage) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func init() {
	proto.RegisterEnum("tinkoff.public.invest.api.contract.v1.OrderDirection", OrderDirection_name, OrderDirection_value)
	proto.RegisterEnum("tinkoff.public.invest.api.contract.v1.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("tinkoff.public.invest.api.contract.v1.OrderExecutionReportStatus", OrderExecutionReportStatus_name, OrderExecutionReportStatus_value)
	proto.RegisterType((*TradesStreamRequest)(nil), "tinkoff.public.invest.api.contract.v1.TradesStreamRequest")
	proto.RegisterType((*TradesStreamResponse)(nil), "tinkoff.public.invest.api.contract.v1.TradesStreamResponse")
	proto.RegisterType((*OrderTrades)(nil), "tinkoff.public.invest.api.contract.v1.OrderTrades")
	proto.RegisterType((*OrderTrade)(nil), "tinkoff.public.invest.api.contract.v1.OrderTrade")
	proto.RegisterType((*PostOrderRequest)(nil), "tinkoff.public.invest.api.contract.v1.PostOrderRequest")
	proto.RegisterType((*PostOrderResponse)(nil), "tinkoff.public.invest.api.contract.v1.PostOrderResponse")
	proto.RegisterType((*CancelOrderRequest)(nil), "tinkoff.public.invest.api.contract.v1.CancelOrderRequest")
	proto.RegisterType((*CancelOrderResponse)(nil), "tinkoff.public.invest.api.contract.v1.CancelOrderResponse")
	proto.RegisterType((*GetOrderStateRequest)(nil), "tinkoff.public.invest.api.contract.v1.GetOrderStateRequest")
	proto.RegisterType((*GetOrdersRequest)(nil), "tinkoff.public.invest.api.contract.v1.GetOrdersRequest")
	proto.RegisterType((*GetOrdersResponse)(nil), "tinkoff.public.invest.api.contract.v1.GetOrdersResponse")
	proto.RegisterType((*OrderState)(nil), "tinkoff.public.invest.api.contract.v1.OrderState")
	proto.RegisterType((*OrderStage)(nil), "tinkoff.public.invest.api.contract.v1.OrderStage")
}

func init() {
	proto.RegisterFile("orders.proto", fileDescriptor_e0f5d4cf0fc9e41b)
}

var fileDescriptor_e0f5d4cf0fc9e41b = []byte{
	// 1390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x41, 0x73, 0xdb, 0x44,
	0x14, 0xae, 0x6c, 0x27, 0xb1, 0x5e, 0x12, 0x57, 0x59, 0xbb, 0xad, 0x6b, 0xca, 0x34, 0xb8, 0x64,
	0x08, 0x65, 0x46, 0x6d, 0xcc, 0x30, 0xa5, 0xed, 0xc9, 0xb5, 0xd5, 0x56, 0xe0, 0x26, 0x46, 0x56,
	0x5a, 0xca, 0x74, 0x10, 0x1b, 0x79, 0xe3, 0xd1, 0x60, 0x4b, 0xaa, 0xb4, 0xce, 0xe0, 0x0b, 0x70,
	0xe0, 0xc2, 0x0c, 0x77, 0xce, 0x70, 0x83, 0x1f, 0xc0, 0x8d, 0x3f, 0xc0, 0x2f, 0xe0, 0x37, 0x30,
	0xc3, 0x7f, 0x60, 0xb4, 0xbb, 0xb2, 0x25, 0x37, 0x29, 0x8a, 0x53, 0x2e, 0x4c, 0x6f, 0xda, 0xd5,
	0x7b, 0xdf, 0xbe, 0xfd, 0xde, 0xdb, 0xf7, 0xde, 0x2e, 0xac, 0x79, 0x41, 0x9f, 0x04, 0xa1, 0xea,
	0x07, 0x1e, 0xf5, 0xd0, 0x16, 0x75, 0xdc, 0x2f, 0xbd, 0xc3, 0x43, 0xd5, 0x1f, 0x1f, 0x0c, 0x1d,
	0x5b, 0x75, 0xdc, 0x23, 0x12, 0x52, 0x15, 0xfb, 0x8e, 0x6a, 0x7b, 0x2e, 0x0d, 0xb0, 0x4d, 0xd5,
	0xa3, 0x9d, 0xda, 0x9a, 0xed, 0x8d, 0x46, 0x9e, 0xcb, 0x95, 0x6a, 0x57, 0x07, 0x9e, 0x37, 0x18,
	0x92, 0x1b, 0x6c, 0x74, 0x30, 0x3e, 0xbc, 0x41, 0x9d, 0x11, 0x09, 0x29, 0x1e, 0xf9, 0x5c, 0xa0,
	0xbe, 0x03, 0x65, 0x33, 0xc0, 0x7d, 0x12, 0xf6, 0x68, 0x40, 0xf0, 0xc8, 0x20, 0xcf, 0xc7, 0x24,
	0xa4, 0xa8, 0x06, 0x45, 0x6c, 0xdb, 0xde, 0xd8, 0xa5, 0x61, 0x55, 0xda, 0xcc, 0x6f, 0xcb, 0xc6,
	0x74, 0x5c, 0xff, 0x5d, 0x82, 0x4a, 0x5a, 0x27, 0xf4, 0x3d, 0x37, 0x24, 0xe8, 0x89, 0xb0, 0xd8,
	0xa2, 0xec, 0x6f, 0x55, 0xda, 0x94, 0xb6, 0x57, 0x1b, 0x0d, 0x35, 0x93, 0xe1, 0xea, 0x5e, 0xa4,
	0xca, 0x71, 0x1f, 0x9e, 0x33, 0x56, 0xbd, 0xd9, 0x10, 0x35, 0xa1, 0xe0, 0x3b, 0xee, 0xa0, 0x9a,
	0x63, 0x80, 0xef, 0x65, 0x04, 0xec, 0x3a, 0xee, 0xe0, 0xe1, 0x39, 0x83, 0xa9, 0xde, 0x93, 0x61,
	0xc5, 0xc7, 0x93, 0xa1, 0x87, 0xfb, 0xf5, 0xdf, 0x72, 0xb0, 0x9a, 0x58, 0x0c, 0x5d, 0x86, 0x22,
	0x37, 0xdb, 0xe9, 0x33, 0x93, 0x65, 0x63, 0x85, 0x8d, 0xf5, 0x3e, 0xba, 0x0d, 0x60, 0x07, 0x04,
	0x53, 0xd2, 0xb7, 0x30, 0x15, 0xcb, 0xd7, 0x54, 0xce, 0xa9, 0x1a, 0x73, 0xaa, 0x9a, 0x31, 0xa7,
	0x86, 0x2c, 0xa4, 0x9b, 0x14, 0xf5, 0x40, 0xee, 0x3b, 0x01, 0xb1, 0xa9, 0xe3, 0xb9, 0xd5, 0xfc,
	0xa6, 0xb4, 0x5d, 0x6a, 0x7c, 0x70, 0x1a, 0x26, 0xda, 0xb1, 0xb2, 0x31, 0xc3, 0x41, 0x08, 0x0a,
	0x87, 0xce, 0xc0, 0xa9, 0x16, 0x98, 0x99, 0xec, 0x1b, 0xe9, 0xb0, 0x2c, 0xf8, 0x5e, 0xda, 0xcc,
	0x6f, 0xaf, 0x36, 0x76, 0x4e, 0xcd, 0xb7, 0x21, 0x00, 0xd0, 0x9b, 0x00, 0xc2, 0xcb, 0x11, 0x17,
	0xcb, 0x6c, 0x11, 0x59, 0xcc, 0xe8, 0xfd, 0xfa, 0x2f, 0x12, 0xc0, 0x4c, 0x0b, 0xdd, 0x02, 0xb9,
	0x8f, 0x29, 0xb1, 0xa2, 0x90, 0x12, 0xbe, 0x7e, 0x19, 0x37, 0xc5, 0x48, 0x38, 0x1a, 0xa2, 0xfb,
	0xb0, 0xe4, 0x07, 0x8e, 0x4d, 0x04, 0xa1, 0x37, 0x33, 0x1a, 0xfc, 0xc9, 0xd8, 0xa3, 0x98, 0x31,
	0xc2, 0xd5, 0xa3, 0x20, 0x7d, 0x3e, 0xc6, 0x2e, 0x75, 0xe8, 0x84, 0x31, 0x9c, 0x37, 0xa6, 0xe3,
	0xfa, 0x5f, 0x39, 0x50, 0xba, 0x5e, 0x48, 0x99, 0xbd, 0x71, 0x54, 0xc7, 0xf4, 0x49, 0x09, 0xfa,
	0x92, 0x20, 0xb9, 0x34, 0xc8, 0xcc, 0xd0, 0xfc, 0xd9, 0x0c, 0x4d, 0xc5, 0x42, 0xe1, 0x15, 0xc5,
	0x42, 0xda, 0x59, 0x4b, 0x73, 0xce, 0x42, 0x7b, 0x00, 0xe2, 0x30, 0x4e, 0x7c, 0xc2, 0x7c, 0x59,
	0xca, 0xbc, 0x01, 0xee, 0xe4, 0x89, 0x4f, 0x0c, 0xd9, 0x8b, 0x3f, 0x53, 0xc7, 0x64, 0x25, 0x75,
	0x4c, 0xea, 0x7f, 0xca, 0xb0, 0x91, 0x20, 0x5b, 0xa4, 0x83, 0x97, 0x9c, 0xab, 0x09, 0x5c, 0x22,
	0x5f, 0x11, 0x7b, 0x1c, 0x6d, 0xc4, 0x0a, 0x88, 0xef, 0x05, 0xd4, 0x0a, 0x29, 0xa6, 0xe3, 0x90,
	0xf9, 0xa0, 0xd4, 0x68, 0x9e, 0xc6, 0x52, 0x2d, 0x86, 0x32, 0x18, 0x52, 0x8f, 0x01, 0x19, 0x17,
	0xc8, 0x71, 0xd3, 0x68, 0x0b, 0x4a, 0x43, 0x8f, 0x86, 0x56, 0xc0, 0x63, 0x82, 0xf4, 0x45, 0xe8,
	0xac, 0x47, 0xb3, 0x46, 0x3c, 0x89, 0xae, 0x01, 0x9b, 0xb0, 0x38, 0x08, 0xe9, 0x33, 0xb7, 0xe5,
	0x8d, 0xb5, 0x68, 0x52, 0x13, 0x73, 0x08, 0x43, 0xd9, 0x71, 0x1d, 0xea, 0xe0, 0xa1, 0xc5, 0x77,
	0xca, 0xa3, 0x65, 0x89, 0x45, 0x4b, 0xd6, 0x73, 0xf8, 0xc8, 0x73, 0xc9, 0xe4, 0x31, 0x1e, 0x8e,
	0x89, 0xb1, 0x21, 0xd0, 0xd8, 0xae, 0xba, 0x2c, 0x74, 0x6c, 0xa8, 0xc4, 0x26, 0xa4, 0xd6, 0x58,
	0x5e, 0x74, 0x0d, 0x14, 0xc3, 0x25, 0x16, 0xb1, 0x00, 0x51, 0x8f, 0x4e, 0x77, 0x81, 0x47, 0x51,
	0x0c, 0x31, 0x27, 0x2f, 0xb4, 0x84, 0xc2, 0xc0, 0x18, 0x7e, 0x93, 0x41, 0xa1, 0x2f, 0x00, 0xc5,
	0x44, 0x45, 0xe5, 0xc9, 0x09, 0xc3, 0xe8, 0x24, 0x14, 0xcf, 0xca, 0x53, 0x6b, 0x8a, 0x85, 0x0e,
	0xa0, 0x3c, 0xe5, 0x29, 0xb1, 0x84, 0x7c, 0x66, 0x9a, 0x12, 0x6b, 0xec, 0x82, 0x8c, 0x6d, 0xc7,
	0x3a, 0x8a, 0x04, 0xaa, 0xb0, 0x28, 0x72, 0x11, 0xdb, 0x0e, 0xfb, 0x9a, 0xa6, 0xa3, 0xd5, 0x44,
	0x3a, 0x4a, 0xa5, 0x8a, 0xb5, 0x57, 0x94, 0x2a, 0x06, 0x70, 0x31, 0xa6, 0x3f, 0x24, 0xf6, 0x38,
	0x70, 0xe8, 0x44, 0x84, 0xd1, 0xfa, 0xa2, 0xbb, 0xa8, 0x08, 0xc0, 0x9e, 0xc0, 0xe3, 0x81, 0x94,
	0x4e, 0x3a, 0xa5, 0xb3, 0x27, 0x9d, 0x2a, 0xac, 0x8c, 0x48, 0x18, 0xe2, 0x01, 0xa9, 0x9e, 0xe7,
	0x29, 0x44, 0x0c, 0x11, 0x99, 0xed, 0x29, 0x71, 0x2e, 0x2c, 0x9f, 0x56, 0x95, 0x05, 0x93, 0x75,
	0xf9, 0x85, 0xd3, 0xd7, 0xa5, 0xf5, 0x5d, 0x40, 0x2d, 0xec, 0xda, 0x64, 0x98, 0x2a, 0x24, 0xe9,
	0xdc, 0x2b, 0xcd, 0xe7, 0xde, 0x64, 0xe6, 0xcb, 0xa5, 0x53, 0xa5, 0x06, 0xe5, 0x14, 0x9e, 0xc8,
	0x95, 0x2a, 0x14, 0x32, 0x96, 0x51, 0x26, 0x57, 0xef, 0x42, 0xe5, 0x01, 0xe1, 0xf9, 0x36, 0xca,
	0x6b, 0xe4, 0xec, 0x86, 0xed, 0x80, 0x12, 0x23, 0x86, 0xd9, 0xd0, 0xea, 0x9f, 0xc3, 0x46, 0x42,
	0x45, 0xec, 0x44, 0x87, 0x65, 0xde, 0xb6, 0xb2, 0xbe, 0xf1, 0x94, 0xed, 0x08, 0xdf, 0x8b, 0x00,
	0xa8, 0xff, 0x0d, 0xa2, 0xdf, 0x60, 0xd3, 0xaf, 0xeb, 0xc9, 0xeb, 0x7a, 0x12, 0xd7, 0x93, 0x01,
	0x5c, 0xc4, 0x47, 0x24, 0xc0, 0x03, 0x62, 0xf9, 0x5e, 0xe8, 0x30, 0xb7, 0xf3, 0x7d, 0x2c, 0x5c,
	0x53, 0x2a, 0x02, 0xb0, 0x2b, 0xf0, 0xf8, 0x4e, 0x8e, 0x2f, 0x5c, 0xf2, 0x7f, 0x5f, 0xb8, 0xe0,
	0x55, 0x16, 0xae, 0xff, 0x5f, 0xa1, 0xd1, 0x61, 0x39, 0xa4, 0x78, 0x40, 0xc2, 0x6a, 0x69, 0xa1,
	0x2c, 0x33, 0x20, 0x86, 0x00, 0x88, 0x5c, 0x1c, 0x92, 0xe0, 0x28, 0x2a, 0x1e, 0x09, 0xfe, 0xcf,
	0x2f, 0xec, 0x62, 0x01, 0x96, 0xa0, 0xbf, 0x06, 0x45, 0x7b, 0x1c, 0x04, 0xc4, 0xb5, 0x27, 0xac,
	0x38, 0xc9, 0xc6, 0x74, 0x3c, 0x57, 0x31, 0x37, 0xce, 0x5e, 0x31, 0x6f, 0xc7, 0x80, 0xd1, 0x75,
	0xab, 0x8a, 0xfe, 0xfd, 0xca, 0xca, 0xa4, 0xdb, 0x98, 0x92, 0xfa, 0x0f, 0xd2, 0x2c, 0xdf, 0x0e,
	0x08, 0x7a, 0x10, 0xdf, 0x7e, 0xa4, 0x45, 0xb9, 0x38, 0xe6, 0x9e, 0x36, 0x7f, 0xc5, 0xba, 0x0c,
	0x45, 0x76, 0xf9, 0x8c, 0x92, 0x7a, 0x9e, 0x27, 0x75, 0x36, 0xd6, 0xfb, 0xd7, 0xfb, 0x50, 0x4a,
	0x47, 0x1a, 0xba, 0x0a, 0x6f, 0xec, 0x19, 0x6d, 0xcd, 0xb0, 0xda, 0xba, 0xa1, 0xb5, 0x4c, 0x7d,
	0x6f, 0xd7, 0xda, 0xdf, 0xed, 0x75, 0xb5, 0x96, 0x7e, 0x5f, 0xd7, 0xda, 0xca, 0x39, 0x74, 0x09,
	0xca, 0xf3, 0x02, 0xf7, 0xf6, 0x9f, 0x2a, 0x12, 0xaa, 0x42, 0x65, 0xfe, 0x47, 0x4f, 0xeb, 0x74,
	0x94, 0xdc, 0x75, 0x13, 0xe4, 0x29, 0x8f, 0xa8, 0x06, 0x17, 0xb9, 0x98, 0xf9, 0xb4, 0xab, 0xcd,
	0x61, 0x57, 0x40, 0x49, 0xfc, 0xeb, 0xe8, 0x8f, 0x74, 0x53, 0x91, 0xd0, 0x05, 0xd8, 0x48, 0xcc,
	0x3e, 0x6a, 0x1a, 0x1f, 0x6b, 0xa6, 0x92, 0xbb, 0xfe, 0x6d, 0x0e, 0x6a, 0x27, 0xd7, 0x12, 0xf4,
	0x0e, 0x5c, 0xd3, 0x3e, 0xd5, 0x5a, 0xfb, 0xcc, 0x10, 0x43, 0xeb, 0xee, 0x19, 0xa6, 0xd5, 0x33,
	0x9b, 0xe6, 0x7e, 0x6f, 0x6e, 0xd1, 0x4d, 0xb8, 0x72, 0x92, 0xe0, 0x7d, 0xbd, 0xd3, 0x51, 0x24,
	0xf4, 0x36, 0x6c, 0x9e, 0x24, 0x61, 0x68, 0x1f, 0x69, 0x2d, 0x53, 0x6b, 0x2b, 0x39, 0xb4, 0x05,
	0x6f, 0x9d, 0x24, 0xd5, 0x6a, 0xee, 0xb6, 0xb4, 0x4e, 0x47, 0x6b, 0x2b, 0xf9, 0x88, 0xe0, 0x93,
	0xc4, 0x76, 0xb5, 0x27, 0x4a, 0x01, 0xbd, 0x0b, 0x5b, 0x27, 0x09, 0x74, 0x9b, 0x86, 0xa9, 0x37,
	0x3b, 0x9d, 0xa7, 0xcc, 0xb0, 0xa5, 0xc6, 0x4f, 0x12, 0x94, 0x79, 0x6f, 0xc0, 0x9f, 0x89, 0x7a,
	0xfc, 0x5c, 0xa0, 0xef, 0x25, 0x58, 0x4b, 0x3e, 0x1f, 0xa1, 0x3b, 0x19, 0x03, 0xeb, 0x98, 0x77,
	0xaa, 0xda, 0xdd, 0x85, 0x74, 0x79, 0xab, 0x72, 0x53, 0x6a, 0xfc, 0x58, 0x80, 0x75, 0x61, 0xa3,
	0xb0, 0xee, 0x6b, 0x90, 0xa7, 0x37, 0x59, 0x74, 0x2b, 0xeb, 0x4b, 0xd3, 0xdc, 0x43, 0x43, 0xed,
	0xc3, 0xd3, 0x2b, 0x8a, 0xf6, 0xe9, 0x3b, 0x09, 0x56, 0x13, 0x0d, 0x22, 0xba, 0x9d, 0x11, 0xe9,
	0xc5, 0x26, 0xb5, 0x76, 0x67, 0x11, 0x55, 0x61, 0xc6, 0x37, 0xb0, 0x9e, 0xea, 0x2f, 0x51, 0x56,
	0xa2, 0x8f, 0xeb, 0x4a, 0x6b, 0xa7, 0xef, 0x01, 0x23, 0x3f, 0x4c, 0x7b, 0xcb, 0xcc, 0x7e, 0x98,
	0x6f, 0x60, 0x33, 0xfb, 0xe1, 0x85, 0x36, 0xf6, 0x1e, 0x86, 0x2b, 0xc1, 0x78, 0xa6, 0xed, 0xcc,
	0x69, 0x74, 0xa5, 0xcf, 0xd6, 0xd4, 0x1b, 0x77, 0x39, 0x1c, 0xf6, 0x9d, 0x9f, 0x73, 0x4b, 0xa6,
	0xde, 0xec, 0xea, 0xbf, 0xe6, 0x2a, 0xa6, 0xd0, 0xd1, 0xd9, 0xbf, 0xa6, 0xef, 0xa8, 0x8f, 0x77,
	0xfe, 0xc8, 0x6d, 0x88, 0xe9, 0x67, 0x7c, 0xfa, 0xd9, 0xe3, 0x9d, 0x83, 0x65, 0x96, 0x8d, 0xdf,
	0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0xef, 0x3c, 0x38, 0x98, 0xe7, 0x15, 0x00, 0x00,
}
