// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sandbox.proto

package investapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Запрос открытия счёта в песочнице.
type OpenSandboxAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSandboxAccountRequest) Reset()         { *m = OpenSandboxAccountRequest{} }
func (m *OpenSandboxAccountRequest) String() string { return proto.CompactTextString(m) }
func (*OpenSandboxAccountRequest) ProtoMessage()    {}
func (*OpenSandboxAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{0}
}

func (m *OpenSandboxAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSandboxAccountRequest.Unmarshal(m, b)
}
func (m *OpenSandboxAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSandboxAccountRequest.Marshal(b, m, deterministic)
}
func (m *OpenSandboxAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSandboxAccountRequest.Merge(m, src)
}
func (m *OpenSandboxAccountRequest) XXX_Size() int {
	return xxx_messageInfo_OpenSandboxAccountRequest.Size(m)
}
func (m *OpenSandboxAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSandboxAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSandboxAccountRequest proto.InternalMessageInfo

//Номер открытого счёта в песочнице.
type OpenSandboxAccountResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSandboxAccountResponse) Reset()         { *m = OpenSandboxAccountResponse{} }
func (m *OpenSandboxAccountResponse) String() string { return proto.CompactTextString(m) }
func (*OpenSandboxAccountResponse) ProtoMessage()    {}
func (*OpenSandboxAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{1}
}

func (m *OpenSandboxAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenSandboxAccountResponse.Unmarshal(m, b)
}
func (m *OpenSandboxAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenSandboxAccountResponse.Marshal(b, m, deterministic)
}
func (m *OpenSandboxAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSandboxAccountResponse.Merge(m, src)
}
func (m *OpenSandboxAccountResponse) XXX_Size() int {
	return xxx_messageInfo_OpenSandboxAccountResponse.Size(m)
}
func (m *OpenSandboxAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSandboxAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSandboxAccountResponse proto.InternalMessageInfo

func (m *OpenSandboxAccountResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//Запрос закрытия счёта в песочнице.
type CloseSandboxAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSandboxAccountRequest) Reset()         { *m = CloseSandboxAccountRequest{} }
func (m *CloseSandboxAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CloseSandboxAccountRequest) ProtoMessage()    {}
func (*CloseSandboxAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{2}
}

func (m *CloseSandboxAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSandboxAccountRequest.Unmarshal(m, b)
}
func (m *CloseSandboxAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSandboxAccountRequest.Marshal(b, m, deterministic)
}
func (m *CloseSandboxAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSandboxAccountRequest.Merge(m, src)
}
func (m *CloseSandboxAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CloseSandboxAccountRequest.Size(m)
}
func (m *CloseSandboxAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSandboxAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSandboxAccountRequest proto.InternalMessageInfo

func (m *CloseSandboxAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//Результат закрытия счёта в песочнице.
type CloseSandboxAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSandboxAccountResponse) Reset()         { *m = CloseSandboxAccountResponse{} }
func (m *CloseSandboxAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CloseSandboxAccountResponse) ProtoMessage()    {}
func (*CloseSandboxAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{3}
}

func (m *CloseSandboxAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSandboxAccountResponse.Unmarshal(m, b)
}
func (m *CloseSandboxAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSandboxAccountResponse.Marshal(b, m, deterministic)
}
func (m *CloseSandboxAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSandboxAccountResponse.Merge(m, src)
}
func (m *CloseSandboxAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CloseSandboxAccountResponse.Size(m)
}
func (m *CloseSandboxAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSandboxAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSandboxAccountResponse proto.InternalMessageInfo

//Запрос пополнения счёта в песочнице.
type SandboxPayInRequest struct {
	AccountId            string      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount               *MoneyValue `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SandboxPayInRequest) Reset()         { *m = SandboxPayInRequest{} }
func (m *SandboxPayInRequest) String() string { return proto.CompactTextString(m) }
func (*SandboxPayInRequest) ProtoMessage()    {}
func (*SandboxPayInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{4}
}

func (m *SandboxPayInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SandboxPayInRequest.Unmarshal(m, b)
}
func (m *SandboxPayInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SandboxPayInRequest.Marshal(b, m, deterministic)
}
func (m *SandboxPayInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandboxPayInRequest.Merge(m, src)
}
func (m *SandboxPayInRequest) XXX_Size() int {
	return xxx_messageInfo_SandboxPayInRequest.Size(m)
}
func (m *SandboxPayInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SandboxPayInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SandboxPayInRequest proto.InternalMessageInfo

func (m *SandboxPayInRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SandboxPayInRequest) GetAmount() *MoneyValue {
	if m != nil {
		return m.Amount
	}
	return nil
}

//Результат пополнения счёта, текущий баланс.
type SandboxPayInResponse struct {
	Balance              *MoneyValue `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SandboxPayInResponse) Reset()         { *m = SandboxPayInResponse{} }
func (m *SandboxPayInResponse) String() string { return proto.CompactTextString(m) }
func (*SandboxPayInResponse) ProtoMessage()    {}
func (*SandboxPayInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fddaeda1f9b863c, []int{5}
}

func (m *SandboxPayInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SandboxPayInResponse.Unmarshal(m, b)
}
func (m *SandboxPayInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SandboxPayInResponse.Marshal(b, m, deterministic)
}
func (m *SandboxPayInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandboxPayInResponse.Merge(m, src)
}
func (m *SandboxPayInResponse) XXX_Size() int {
	return xxx_messageInfo_SandboxPayInResponse.Size(m)
}
func (m *SandboxPayInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SandboxPayInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SandboxPayInResponse proto.InternalMessageInfo

func (m *SandboxPayInResponse) GetBalance() *MoneyValue {
	if m != nil {
		return m.Balance
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenSandboxAccountRequest)(nil), "tinkoff.public.invest.api.contract.v1.OpenSandboxAccountRequest")
	proto.RegisterType((*OpenSandboxAccountResponse)(nil), "tinkoff.public.invest.api.contract.v1.OpenSandboxAccountResponse")
	proto.RegisterType((*CloseSandboxAccountRequest)(nil), "tinkoff.public.invest.api.contract.v1.CloseSandboxAccountRequest")
	proto.RegisterType((*CloseSandboxAccountResponse)(nil), "tinkoff.public.invest.api.contract.v1.CloseSandboxAccountResponse")
	proto.RegisterType((*SandboxPayInRequest)(nil), "tinkoff.public.invest.api.contract.v1.SandboxPayInRequest")
	proto.RegisterType((*SandboxPayInResponse)(nil), "tinkoff.public.invest.api.contract.v1.SandboxPayInResponse")
}

func init() {
	proto.RegisterFile("sandbox.proto", fileDescriptor_6fddaeda1f9b863c)
}

var fileDescriptor_6fddaeda1f9b863c = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x99, 0x80, 0x95, 0xbe, 0x8d, 0x52, 0x27, 0x39, 0xd4, 0xad, 0x85, 0x12, 0x10, 0x7a,
	0x1a, 0x49, 0x3d, 0xd8, 0x36, 0x17, 0xd3, 0x1e, 0xc2, 0x22, 0xd2, 0x90, 0x94, 0x1c, 0xa4, 0x20,
	0x93, 0xcd, 0x04, 0x06, 0x37, 0x33, 0xeb, 0xce, 0x6c, 0xb0, 0x27, 0x4f, 0xfe, 0x01, 0x3f, 0x81,
	0xe0, 0xc9, 0xa3, 0x07, 0x3f, 0x88, 0x9f, 0x4a, 0xb2, 0x33, 0x9b, 0x6c, 0xe2, 0x16, 0x67, 0xb7,
	0xb7, 0x64, 0x5e, 0x7e, 0xcf, 0xfb, 0xcc, 0x33, 0x6f, 0x66, 0x02, 0x0f, 0x14, 0x15, 0x93, 0xb1,
	0xfc, 0x40, 0xa2, 0x58, 0x6a, 0x89, 0x9f, 0x6a, 0x2e, 0xde, 0xc9, 0xe9, 0x94, 0x44, 0xc9, 0x38,
	0xe4, 0x01, 0xe1, 0x62, 0xce, 0x94, 0x26, 0x34, 0xe2, 0x24, 0x90, 0x42, 0xc7, 0x34, 0xd0, 0x64,
	0xde, 0xf6, 0xea, 0x81, 0x9c, 0xcd, 0xa4, 0x30, 0x90, 0x57, 0x97, 0xf1, 0x84, 0xc5, 0xca, 0x7e,
	0xdb, 0x95, 0x11, 0x8b, 0xa9, 0xe6, 0x52, 0x64, 0x2b, 0x3b, 0x89, 0x5a, 0x96, 0x5b, 0xfb, 0xf0,
	0xf8, 0x32, 0x62, 0x62, 0x68, 0xda, 0x76, 0x83, 0x40, 0x26, 0x42, 0x0f, 0xd8, 0xfb, 0x84, 0x29,
	0xdd, 0xea, 0x80, 0x57, 0x54, 0x54, 0x91, 0x14, 0x8a, 0xe1, 0x03, 0x00, 0x6a, 0x96, 0xde, 0xf2,
	0xc9, 0x1e, 0x3a, 0x44, 0x47, 0xdb, 0x83, 0x6d, 0xbb, 0xe2, 0x4f, 0x16, 0xf0, 0x45, 0x28, 0x15,
	0x2b, 0x94, 0xfe, 0x1f, 0x7c, 0x00, 0xfb, 0x85, 0xb0, 0x69, 0xdd, 0xfa, 0x08, 0x0d, 0x5b, 0xe9,
	0xd3, 0x1b, 0x5f, 0xb8, 0x89, 0x62, 0x1f, 0xb6, 0xe8, 0x6c, 0xf1, 0x79, 0xaf, 0x76, 0x88, 0x8e,
	0x76, 0x8e, 0xdb, 0xc4, 0x29, 0x5e, 0xf2, 0x5a, 0x0a, 0x76, 0x33, 0xa2, 0x61, 0xc2, 0x06, 0x56,
	0xa0, 0x15, 0x40, 0x73, 0xdd, 0x80, 0xcd, 0xe4, 0x15, 0xdc, 0x1f, 0xd3, 0x90, 0x8a, 0x80, 0xa5,
	0xed, 0x2b, 0xf5, 0xc8, 0x14, 0x8e, 0x7f, 0xd7, 0xe1, 0xa1, 0xed, 0x32, 0x64, 0xf1, 0x9c, 0x07,
	0x0c, 0x7f, 0x47, 0x80, 0xff, 0x3d, 0x12, 0xfc, 0xd2, 0xb1, 0xcb, 0xad, 0x47, 0xed, 0x75, 0xef,
	0xa0, 0x60, 0xf7, 0xfe, 0x0d, 0x01, 0xee, 0x31, 0xbd, 0x5e, 0x55, 0xf8, 0xd4, 0x51, 0xb9, 0xc7,
	0x74, 0xc6, 0x64, 0xa6, 0xce, 0xaa, 0xa0, 0xd6, 0xcd, 0x0f, 0x04, 0x8d, 0x82, 0x11, 0xc2, 0xae,
	0x1b, 0xbd, 0x7d, 0x76, 0xbd, 0xf3, 0xbb, 0x48, 0x58, 0x7b, 0x9f, 0x10, 0xec, 0xf6, 0xa5, 0xca,
	0xd2, 0xba, 0x5c, 0xfc, 0x64, 0xf1, 0x0b, 0x47, 0xe1, 0x05, 0x98, 0x12, 0x99, 0xa3, 0x93, 0xf2,
	0x60, 0xce, 0xc7, 0xea, 0xd0, 0xd2, 0x9a, 0x72, 0xf6, 0xd1, 0x63, 0x46, 0x4d, 0x95, 0xf5, 0x91,
	0x03, 0x73, 0xc3, 0x73, 0xb1, 0x98, 0xfa, 0x70, 0x2d, 0x11, 0xd7, 0xe1, 0x31, 0xe8, 0x5a, 0x26,
	0x67, 0x55, 0x50, 0xeb, 0xe6, 0x33, 0x82, 0xe6, 0x46, 0x2a, 0x43, 0x4d, 0x35, 0xc3, 0x9d, 0x92,
	0x1b, 0x4c, 0xa9, 0xcc, 0x91, 0xeb, 0x5d, 0x90, 0xeb, 0xf7, 0x15, 0x41, 0x63, 0x65, 0xa4, 0x2f,
	0x15, 0x4f, 0x6f, 0xf2, 0x32, 0x93, 0x62, 0x88, 0x0a, 0x93, 0x92, 0x81, 0xab, 0x13, 0xca, 0x67,
	0xb2, 0x7c, 0x55, 0xf0, 0x89, 0xfb, 0xd5, 0x61, 0x91, 0xcc, 0xcc, 0x69, 0x05, 0xd2, 0xba, 0xd9,
	0x0c, 0x26, 0xd6, 0x53, 0x19, 0x72, 0x59, 0x22, 0x18, 0x4b, 0x94, 0x0f, 0x66, 0x09, 0x5a, 0x2b,
	0x5f, 0x10, 0xd4, 0xf3, 0x8f, 0x01, 0x76, 0x9d, 0xbc, 0x82, 0x27, 0xcc, 0xeb, 0x54, 0x62, 0x8d,
	0x93, 0x73, 0x0a, 0x4f, 0xe2, 0x64, 0x25, 0xc0, 0x37, 0xa0, 0x3e, 0x7a, 0x53, 0x27, 0xcf, 0x3a,
	0x46, 0x91, 0x46, 0xfc, 0x67, 0xed, 0xde, 0x95, 0xdf, 0xed, 0xfb, 0xbf, 0x6a, 0xcd, 0x2b, 0xcb,
	0xf8, 0x69, 0xad, 0x1b, 0x71, 0x32, 0x6a, 0xff, 0xa9, 0x3d, 0xb2, 0xcb, 0xd7, 0x66, 0xf9, 0x7a,
	0xd4, 0x1e, 0x6f, 0xa5, 0x7f, 0x1b, 0x9e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x06, 0x64,
	0xf5, 0xa9, 0x08, 0x00, 0x00,
}
