// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package investapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Тип счёта.
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_TINKOFF     AccountType = 1
	AccountType_ACCOUNT_TYPE_TINKOFF_IIS AccountType = 2
	AccountType_ACCOUNT_TYPE_INVEST_BOX  AccountType = 3
)

var AccountType_name = map[int32]string{
	0: "ACCOUNT_TYPE_UNSPECIFIED",
	1: "ACCOUNT_TYPE_TINKOFF",
	2: "ACCOUNT_TYPE_TINKOFF_IIS",
	3: "ACCOUNT_TYPE_INVEST_BOX",
}

var AccountType_value = map[string]int32{
	"ACCOUNT_TYPE_UNSPECIFIED": 0,
	"ACCOUNT_TYPE_TINKOFF":     1,
	"ACCOUNT_TYPE_TINKOFF_IIS": 2,
	"ACCOUNT_TYPE_INVEST_BOX":  3,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

//Статус счёта.
type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_NEW         AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_OPEN        AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 3
)

var AccountStatus_name = map[int32]string{
	0: "ACCOUNT_STATUS_UNSPECIFIED",
	1: "ACCOUNT_STATUS_NEW",
	2: "ACCOUNT_STATUS_OPEN",
	3: "ACCOUNT_STATUS_CLOSED",
}

var AccountStatus_value = map[string]int32{
	"ACCOUNT_STATUS_UNSPECIFIED": 0,
	"ACCOUNT_STATUS_NEW":         1,
	"ACCOUNT_STATUS_OPEN":        2,
	"ACCOUNT_STATUS_CLOSED":      3,
}

func (x AccountStatus) String() string {
	return proto.EnumName(AccountStatus_name, int32(x))
}

func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

//Уровень доступа к счёту.
type AccessLevel int32

const (
	AccessLevel_ACCOUNT_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	AccessLevel_ACCOUNT_ACCESS_LEVEL_FULL_ACCESS AccessLevel = 1
	AccessLevel_ACCOUNT_ACCESS_LEVEL_READ_ONLY   AccessLevel = 2
	AccessLevel_ACCOUNT_ACCESS_LEVEL_NO_ACCESS   AccessLevel = 3
)

var AccessLevel_name = map[int32]string{
	0: "ACCOUNT_ACCESS_LEVEL_UNSPECIFIED",
	1: "ACCOUNT_ACCESS_LEVEL_FULL_ACCESS",
	2: "ACCOUNT_ACCESS_LEVEL_READ_ONLY",
	3: "ACCOUNT_ACCESS_LEVEL_NO_ACCESS",
}

var AccessLevel_value = map[string]int32{
	"ACCOUNT_ACCESS_LEVEL_UNSPECIFIED": 0,
	"ACCOUNT_ACCESS_LEVEL_FULL_ACCESS": 1,
	"ACCOUNT_ACCESS_LEVEL_READ_ONLY":   2,
	"ACCOUNT_ACCESS_LEVEL_NO_ACCESS":   3,
}

func (x AccessLevel) String() string {
	return proto.EnumName(AccessLevel_name, int32(x))
}

func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

//Запрос получения счетов пользователя.
type GetAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(m, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

//Список счетов пользователя.
type GetAccountsResponse struct {
	// Массив счетов клиента.
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

//Информация о счёте.
type Account struct {
	// Идентификатор счёта.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Тип счёта.
	Type AccountType `protobuf:"varint,2,opt,name=type,proto3,enum=tinkoff.public.invest.api.contract.v1.AccountType" json:"type,omitempty"`
	// Название счёта.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Статус счёта.
	Status AccountStatus `protobuf:"varint,4,opt,name=status,proto3,enum=tinkoff.public.invest.api.contract.v1.AccountStatus" json:"status,omitempty"`
	// Дата открытия счёта в часовом поясе UTC.
	OpenedDate *timestamp.Timestamp `protobuf:"bytes,5,opt,name=opened_date,json=openedDate,proto3" json:"opened_date,omitempty"`
	// Дата закрытия счёта в часовом поясе UTC.
	ClosedDate *timestamp.Timestamp `protobuf:"bytes,6,opt,name=closed_date,json=closedDate,proto3" json:"closed_date,omitempty"`
	// Уровень доступа к текущему счёту (определяется токеном).
	AccessLevel          AccessLevel `protobuf:"varint,7,opt,name=access_level,json=accessLevel,proto3,enum=tinkoff.public.invest.api.contract.v1.AccessLevel" json:"access_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (m *Account) GetOpenedDate() *timestamp.Timestamp {
	if m != nil {
		return m.OpenedDate
	}
	return nil
}

func (m *Account) GetClosedDate() *timestamp.Timestamp {
	if m != nil {
		return m.ClosedDate
	}
	return nil
}

func (m *Account) GetAccessLevel() AccessLevel {
	if m != nil {
		return m.AccessLevel
	}
	return AccessLevel_ACCOUNT_ACCESS_LEVEL_UNSPECIFIED
}

//Запрос маржинальных показателей по счёту
type GetMarginAttributesRequest struct {
	// Идентификатор счёта пользователя.
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMarginAttributesRequest) Reset()         { *m = GetMarginAttributesRequest{} }
func (m *GetMarginAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMarginAttributesRequest) ProtoMessage()    {}
func (*GetMarginAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *GetMarginAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarginAttributesRequest.Unmarshal(m, b)
}
func (m *GetMarginAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarginAttributesRequest.Marshal(b, m, deterministic)
}
func (m *GetMarginAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarginAttributesRequest.Merge(m, src)
}
func (m *GetMarginAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMarginAttributesRequest.Size(m)
}
func (m *GetMarginAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarginAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarginAttributesRequest proto.InternalMessageInfo

func (m *GetMarginAttributesRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

//Маржинальные показатели по счёту.
type GetMarginAttributesResponse struct {
	// Ликвидная стоимость портфеля. Подробнее: [что такое ликвидный портфель?](https://help.tinkoff.ru/margin-trade/short/liquid-portfolio/).
	LiquidPortfolio *MoneyValue `protobuf:"bytes,1,opt,name=liquid_portfolio,json=liquidPortfolio,proto3" json:"liquid_portfolio,omitempty"`
	// Начальная маржа — начальное обеспечение для совершения новой сделки. Подробнее: [начальная и минимальная маржа](https://help.tinkoff.ru/margin-trade/short/initial-and-maintenance-margin/).
	StartingMargin *MoneyValue `protobuf:"bytes,2,opt,name=starting_margin,json=startingMargin,proto3" json:"starting_margin,omitempty"`
	// Минимальная маржа — это минимальное обеспечение для поддержания позиции, которую вы уже открыли. Подробнее: [начальная и минимальная маржа](https://help.tinkoff.ru/margin-trade/short/initial-and-maintenance-margin/).
	MinimalMargin *MoneyValue `protobuf:"bytes,3,opt,name=minimal_margin,json=minimalMargin,proto3" json:"minimal_margin,omitempty"`
	// Уровень достаточности средств. Соотношение стоимости ликвидного портфеля к начальной марже.
	FundsSufficiencyLevel *Quotation `protobuf:"bytes,4,opt,name=funds_sufficiency_level,json=fundsSufficiencyLevel,proto3" json:"funds_sufficiency_level,omitempty"`
	// Объем недостающих средств. Разница между стартовой маржой и ликвидной стоимости портфеля.
	AmountOfMissingFunds *MoneyValue `protobuf:"bytes,5,opt,name=amount_of_missing_funds,json=amountOfMissingFunds,proto3" json:"amount_of_missing_funds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMarginAttributesResponse) Reset()         { *m = GetMarginAttributesResponse{} }
func (m *GetMarginAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMarginAttributesResponse) ProtoMessage()    {}
func (*GetMarginAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *GetMarginAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMarginAttributesResponse.Unmarshal(m, b)
}
func (m *GetMarginAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMarginAttributesResponse.Marshal(b, m, deterministic)
}
func (m *GetMarginAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMarginAttributesResponse.Merge(m, src)
}
func (m *GetMarginAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMarginAttributesResponse.Size(m)
}
func (m *GetMarginAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMarginAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMarginAttributesResponse proto.InternalMessageInfo

func (m *GetMarginAttributesResponse) GetLiquidPortfolio() *MoneyValue {
	if m != nil {
		return m.LiquidPortfolio
	}
	return nil
}

func (m *GetMarginAttributesResponse) GetStartingMargin() *MoneyValue {
	if m != nil {
		return m.StartingMargin
	}
	return nil
}

func (m *GetMarginAttributesResponse) GetMinimalMargin() *MoneyValue {
	if m != nil {
		return m.MinimalMargin
	}
	return nil
}

func (m *GetMarginAttributesResponse) GetFundsSufficiencyLevel() *Quotation {
	if m != nil {
		return m.FundsSufficiencyLevel
	}
	return nil
}

func (m *GetMarginAttributesResponse) GetAmountOfMissingFunds() *MoneyValue {
	if m != nil {
		return m.AmountOfMissingFunds
	}
	return nil
}

//Запрос текущих лимитов пользователя.
type GetUserTariffRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserTariffRequest) Reset()         { *m = GetUserTariffRequest{} }
func (m *GetUserTariffRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserTariffRequest) ProtoMessage()    {}
func (*GetUserTariffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *GetUserTariffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserTariffRequest.Unmarshal(m, b)
}
func (m *GetUserTariffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserTariffRequest.Marshal(b, m, deterministic)
}
func (m *GetUserTariffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserTariffRequest.Merge(m, src)
}
func (m *GetUserTariffRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserTariffRequest.Size(m)
}
func (m *GetUserTariffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserTariffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserTariffRequest proto.InternalMessageInfo

//Текущие лимиты пользователя.
type GetUserTariffResponse struct {
	UnaryLimits          []*UnaryLimit  `protobuf:"bytes,1,rep,name=unary_limits,json=unaryLimits,proto3" json:"unary_limits,omitempty"`
	StreamLimits         []*StreamLimit `protobuf:"bytes,2,rep,name=stream_limits,json=streamLimits,proto3" json:"stream_limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetUserTariffResponse) Reset()         { *m = GetUserTariffResponse{} }
func (m *GetUserTariffResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserTariffResponse) ProtoMessage()    {}
func (*GetUserTariffResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *GetUserTariffResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserTariffResponse.Unmarshal(m, b)
}
func (m *GetUserTariffResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserTariffResponse.Marshal(b, m, deterministic)
}
func (m *GetUserTariffResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserTariffResponse.Merge(m, src)
}
func (m *GetUserTariffResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserTariffResponse.Size(m)
}
func (m *GetUserTariffResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserTariffResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserTariffResponse proto.InternalMessageInfo

func (m *GetUserTariffResponse) GetUnaryLimits() []*UnaryLimit {
	if m != nil {
		return m.UnaryLimits
	}
	return nil
}

func (m *GetUserTariffResponse) GetStreamLimits() []*StreamLimit {
	if m != nil {
		return m.StreamLimits
	}
	return nil
}

//Лимит unary-методов.
type UnaryLimit struct {
	LimitPerMinute       int32    `protobuf:"varint,1,opt,name=limit_per_minute,json=limitPerMinute,proto3" json:"limit_per_minute,omitempty"`
	Methods              []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryLimit) Reset()         { *m = UnaryLimit{} }
func (m *UnaryLimit) String() string { return proto.CompactTextString(m) }
func (*UnaryLimit) ProtoMessage()    {}
func (*UnaryLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *UnaryLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryLimit.Unmarshal(m, b)
}
func (m *UnaryLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryLimit.Marshal(b, m, deterministic)
}
func (m *UnaryLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryLimit.Merge(m, src)
}
func (m *UnaryLimit) XXX_Size() int {
	return xxx_messageInfo_UnaryLimit.Size(m)
}
func (m *UnaryLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryLimit.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryLimit proto.InternalMessageInfo

func (m *UnaryLimit) GetLimitPerMinute() int32 {
	if m != nil {
		return m.LimitPerMinute
	}
	return 0
}

func (m *UnaryLimit) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

//Лимит stream-соединений.
type StreamLimit struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Streams              []string `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamLimit) Reset()         { *m = StreamLimit{} }
func (m *StreamLimit) String() string { return proto.CompactTextString(m) }
func (*StreamLimit) ProtoMessage()    {}
func (*StreamLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{8}
}

func (m *StreamLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamLimit.Unmarshal(m, b)
}
func (m *StreamLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamLimit.Marshal(b, m, deterministic)
}
func (m *StreamLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamLimit.Merge(m, src)
}
func (m *StreamLimit) XXX_Size() int {
	return xxx_messageInfo_StreamLimit.Size(m)
}
func (m *StreamLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamLimit.DiscardUnknown(m)
}

var xxx_messageInfo_StreamLimit proto.InternalMessageInfo

func (m *StreamLimit) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *StreamLimit) GetStreams() []string {
	if m != nil {
		return m.Streams
	}
	return nil
}

//Запрос информации о пользователе.
type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{9}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

//Информация о пользователе.
type GetInfoResponse struct {
	PremStatus           bool     `protobuf:"varint,1,opt,name=prem_status,json=premStatus,proto3" json:"prem_status,omitempty"`
	QualStatus           bool     `protobuf:"varint,2,opt,name=qual_status,json=qualStatus,proto3" json:"qual_status,omitempty"`
	QualifiedForWorkWith []string `protobuf:"bytes,3,rep,name=qualified_for_work_with,json=qualifiedForWorkWith,proto3" json:"qualified_for_work_with,omitempty"`
	Tariff               string   `protobuf:"bytes,4,opt,name=tariff,proto3" json:"tariff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{10}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetPremStatus() bool {
	if m != nil {
		return m.PremStatus
	}
	return false
}

func (m *GetInfoResponse) GetQualStatus() bool {
	if m != nil {
		return m.QualStatus
	}
	return false
}

func (m *GetInfoResponse) GetQualifiedForWorkWith() []string {
	if m != nil {
		return m.QualifiedForWorkWith
	}
	return nil
}

func (m *GetInfoResponse) GetTariff() string {
	if m != nil {
		return m.Tariff
	}
	return ""
}

func init() {
	proto.RegisterEnum("tinkoff.public.invest.api.contract.v1.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("tinkoff.public.invest.api.contract.v1.AccountStatus", AccountStatus_name, AccountStatus_value)
	proto.RegisterEnum("tinkoff.public.invest.api.contract.v1.AccessLevel", AccessLevel_name, AccessLevel_value)
	proto.RegisterType((*GetAccountsRequest)(nil), "tinkoff.public.invest.api.contract.v1.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "tinkoff.public.invest.api.contract.v1.GetAccountsResponse")
	proto.RegisterType((*Account)(nil), "tinkoff.public.invest.api.contract.v1.Account")
	proto.RegisterType((*GetMarginAttributesRequest)(nil), "tinkoff.public.invest.api.contract.v1.GetMarginAttributesRequest")
	proto.RegisterType((*GetMarginAttributesResponse)(nil), "tinkoff.public.invest.api.contract.v1.GetMarginAttributesResponse")
	proto.RegisterType((*GetUserTariffRequest)(nil), "tinkoff.public.invest.api.contract.v1.GetUserTariffRequest")
	proto.RegisterType((*GetUserTariffResponse)(nil), "tinkoff.public.invest.api.contract.v1.GetUserTariffResponse")
	proto.RegisterType((*UnaryLimit)(nil), "tinkoff.public.invest.api.contract.v1.UnaryLimit")
	proto.RegisterType((*StreamLimit)(nil), "tinkoff.public.invest.api.contract.v1.StreamLimit")
	proto.RegisterType((*GetInfoRequest)(nil), "tinkoff.public.invest.api.contract.v1.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "tinkoff.public.invest.api.contract.v1.GetInfoResponse")
}

func init() {
	proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea)
}

var fileDescriptor_030765f334c86cea = []byte{
	// 1088 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0x4f, 0x4f, 0xe3, 0xc6,
	0x1b, 0xc7, 0x7f, 0x4e, 0x02, 0x2c, 0x4f, 0x42, 0x36, 0xbf, 0xd9, 0x00, 0x69, 0x76, 0xbb, 0x8b,
	0xa2, 0x56, 0x42, 0x1c, 0x4c, 0x49, 0xbb, 0x95, 0x5a, 0xda, 0x43, 0x08, 0x09, 0x4a, 0x1b, 0x92,
	0xd4, 0x76, 0x60, 0x77, 0x85, 0x64, 0x0d, 0xce, 0x18, 0x46, 0xc4, 0x1e, 0xe3, 0x19, 0xb3, 0x45,
	0xbd, 0xf4, 0xd0, 0x5e, 0x7a, 0xee, 0xb1, 0x97, 0xee, 0xb1, 0x6f, 0xa1, 0xf7, 0x1e, 0xfa, 0xaa,
	0x2a, 0x8f, 0xc7, 0x01, 0xc2, 0xa2, 0x06, 0x7a, 0xcb, 0xf3, 0xe7, 0xfb, 0x99, 0xc7, 0x7e, 0x1e,
	0x3f, 0x19, 0xc8, 0x47, 0x9c, 0x84, 0x5c, 0x0f, 0x42, 0x26, 0x18, 0xfa, 0x58, 0x50, 0xff, 0x8c,
	0xb9, 0xae, 0x1e, 0x44, 0xc7, 0x63, 0xea, 0xe8, 0xd4, 0xbf, 0x20, 0x5c, 0xe8, 0x38, 0xa0, 0xba,
	0xc3, 0x7c, 0x11, 0x62, 0x47, 0xe8, 0x17, 0x5b, 0xd5, 0x17, 0x27, 0x8c, 0x9d, 0x8c, 0xc9, 0xa6,
	0x14, 0x1d, 0x47, 0xee, 0xa6, 0xa0, 0x1e, 0xe1, 0x02, 0x7b, 0x41, 0xc2, 0xa9, 0x16, 0x1c, 0xe6,
	0x79, 0xcc, 0x4f, 0xac, 0x5a, 0x19, 0xd0, 0x1e, 0x11, 0x0d, 0xc7, 0x61, 0x91, 0x2f, 0xb8, 0x41,
	0xce, 0x23, 0xc2, 0x45, 0x0d, 0xc3, 0x93, 0x1b, 0x5e, 0x1e, 0x30, 0x9f, 0x13, 0xf4, 0x0d, 0x3c,
	0xc2, 0xca, 0x57, 0xd1, 0xd6, 0xb2, 0xeb, 0xf9, 0xba, 0xae, 0xcf, 0x54, 0x95, 0xae, 0x50, 0xc6,
	0x44, 0x5f, 0xfb, 0x35, 0x0b, 0x0b, 0xca, 0x8b, 0x8a, 0x90, 0xa1, 0xa3, 0x8a, 0xb6, 0xa6, 0xad,
	0x2f, 0x1a, 0x19, 0x3a, 0x42, 0x6d, 0xc8, 0x89, 0xcb, 0x80, 0x54, 0x32, 0x6b, 0xda, 0x7a, 0xb1,
	0x5e, 0xbf, 0xdf, 0x19, 0xd6, 0x65, 0x40, 0x0c, 0xa9, 0x47, 0x08, 0x72, 0x3e, 0xf6, 0x48, 0x25,
	0x2b, 0xc9, 0xf2, 0x37, 0xea, 0xc2, 0x3c, 0x17, 0x58, 0x44, 0xbc, 0x92, 0x93, 0xf4, 0xcf, 0xee,
	0x47, 0x37, 0xa5, 0xd6, 0x50, 0x0c, 0xb4, 0x0d, 0x79, 0x16, 0x10, 0x9f, 0x8c, 0xec, 0x11, 0x16,
	0xa4, 0x32, 0xb7, 0xa6, 0xad, 0xe7, 0xeb, 0x55, 0x3d, 0xe9, 0x81, 0x9e, 0xf6, 0x40, 0xb7, 0xd2,
	0x1e, 0x18, 0x90, 0xa4, 0xef, 0x62, 0x41, 0x62, 0xb1, 0x33, 0x66, 0x3c, 0x15, 0xcf, 0xff, 0xbb,
	0x38, 0x49, 0x97, 0xe2, 0x21, 0x14, 0xb0, 0xe3, 0x10, 0xce, 0xed, 0x31, 0xb9, 0x20, 0xe3, 0xca,
	0xc2, 0x7d, 0xdf, 0x15, 0xe1, 0xbc, 0x1b, 0x2b, 0x8d, 0x3c, 0xbe, 0x32, 0x6a, 0xdb, 0x50, 0xdd,
	0x23, 0x62, 0x1f, 0x87, 0x27, 0xd4, 0x6f, 0x08, 0x11, 0xd2, 0xe3, 0x48, 0x90, 0x74, 0x2e, 0xd0,
	0x87, 0x00, 0xaa, 0x81, 0xf6, 0xa4, 0x61, 0x8b, 0xca, 0xd3, 0x19, 0xd5, 0x7e, 0xce, 0xc1, 0xd3,
	0xf7, 0xaa, 0xd5, 0xfc, 0x1c, 0x41, 0x69, 0x4c, 0xcf, 0x23, 0x3a, 0xb2, 0x03, 0x16, 0x0a, 0x97,
	0x8d, 0x29, 0x93, 0x90, 0x7c, 0x7d, 0x6b, 0xc6, 0xba, 0xf7, 0x99, 0x4f, 0x2e, 0x0f, 0xf0, 0x38,
	0x22, 0xc6, 0xe3, 0x04, 0x35, 0x48, 0x49, 0xe8, 0x0d, 0x3c, 0xe6, 0x02, 0x87, 0x82, 0xfa, 0x27,
	0xb6, 0x27, 0x4b, 0x90, 0x03, 0xf4, 0x20, 0x78, 0x31, 0x25, 0x25, 0xcf, 0x82, 0x5e, 0x41, 0xd1,
	0xa3, 0x3e, 0xf5, 0xf0, 0x38, 0x45, 0x67, 0x1f, 0x8a, 0x5e, 0x52, 0x20, 0x45, 0x3e, 0x85, 0x55,
	0x37, 0xf2, 0x47, 0xdc, 0xe6, 0x91, 0xeb, 0x52, 0x87, 0x12, 0xdf, 0xb9, 0x54, 0x2d, 0xcd, 0xc9,
	0x23, 0x3e, 0x99, 0xf1, 0x88, 0xef, 0x22, 0x26, 0xb0, 0xa0, 0xcc, 0x37, 0x96, 0x25, 0xd0, 0xbc,
	0xe2, 0xc9, 0xd6, 0xc6, 0x27, 0x61, 0x4f, 0xf6, 0x8e, 0xb9, 0xb6, 0x47, 0x39, 0x8f, 0x5f, 0x94,
	0x4c, 0x55, 0x73, 0xfb, 0x80, 0x87, 0x29, 0x27, 0xc4, 0xbe, 0xbb, 0x9f, 0xf0, 0xda, 0x31, 0xae,
	0xb6, 0x02, 0xe5, 0x3d, 0x22, 0x86, 0x9c, 0x84, 0x16, 0x0e, 0xa9, 0xeb, 0xa6, 0x6b, 0xe5, 0x2f,
	0x0d, 0x96, 0xa7, 0x02, 0x6a, 0x32, 0x2c, 0x28, 0x44, 0x3e, 0x0e, 0x2f, 0xed, 0x31, 0xf5, 0xe8,
	0x64, 0xbb, 0xcc, 0x5a, 0xd0, 0x30, 0x96, 0x76, 0x63, 0xa5, 0x91, 0x8f, 0x26, 0xbf, 0x39, 0x3a,
	0x84, 0x25, 0x2e, 0x42, 0x82, 0xbd, 0x14, 0x9b, 0x91, 0xd8, 0x59, 0x3f, 0x12, 0x53, 0x6a, 0x13,
	0x6e, 0x81, 0x5f, 0x19, 0xbc, 0x36, 0x00, 0xb8, 0x3a, 0x13, 0xad, 0xc7, 0x63, 0xed, 0x51, 0x61,
	0x07, 0x24, 0xb4, 0x3d, 0xea, 0x47, 0x82, 0xc8, 0xb1, 0x9e, 0x33, 0x8a, 0xd2, 0x3f, 0x20, 0xe1,
	0xbe, 0xf4, 0xa2, 0x0a, 0x2c, 0x78, 0x44, 0x9c, 0xb2, 0x51, 0x52, 0xca, 0xa2, 0x91, 0x9a, 0xb5,
	0xaf, 0x21, 0x7f, 0xed, 0x38, 0x54, 0x86, 0x39, 0x29, 0x55, 0x9c, 0xc4, 0x88, 0xe5, 0x49, 0x19,
	0x13, 0xb9, 0x32, 0x6b, 0x25, 0x28, 0xee, 0x11, 0xd1, 0xf1, 0x5d, 0x96, 0xbe, 0xeb, 0x77, 0x1a,
	0x3c, 0x9e, 0xb8, 0xd4, 0x5b, 0x7e, 0x01, 0xf9, 0x20, 0x24, 0x9e, 0xad, 0x16, 0x60, 0xcc, 0x7e,
	0x64, 0x40, 0xec, 0x4a, 0xd6, 0x5a, 0x9c, 0x70, 0x1e, 0xe1, 0x71, 0x9a, 0x90, 0x49, 0x12, 0x62,
	0x97, 0x4a, 0x78, 0x09, 0xab, 0xb1, 0x45, 0x5d, 0x4a, 0x46, 0xb6, 0xcb, 0x42, 0xfb, 0x2d, 0x0b,
	0xcf, 0xec, 0xb7, 0x54, 0x9c, 0x56, 0xb2, 0xb2, 0xa2, 0xf2, 0x24, 0xdc, 0x66, 0xe1, 0x21, 0x0b,
	0xcf, 0x0e, 0xa9, 0x38, 0x45, 0x2b, 0x30, 0x2f, 0x64, 0xc3, 0xe5, 0x4c, 0x2f, 0x1a, 0xca, 0xda,
	0xf8, 0x51, 0x83, 0xfc, 0xb5, 0xb5, 0x8d, 0x9e, 0x41, 0xa5, 0xd1, 0x6c, 0xf6, 0x87, 0x3d, 0xcb,
	0xb6, 0x5e, 0x0f, 0x5a, 0xf6, 0xb0, 0x67, 0x0e, 0x5a, 0xcd, 0x4e, 0xbb, 0xd3, 0xda, 0x2d, 0xfd,
	0x0f, 0x55, 0xa0, 0x7c, 0x23, 0x6a, 0x75, 0x7a, 0xdf, 0xf6, 0xdb, 0xed, 0x92, 0x76, 0x4b, 0xa7,
	0x22, 0x76, 0xa7, 0x63, 0x96, 0x32, 0xe8, 0x29, 0xac, 0xde, 0x88, 0x76, 0x7a, 0x07, 0x2d, 0xd3,
	0xb2, 0x77, 0xfa, 0xaf, 0x4a, 0xd9, 0x8d, 0x1f, 0x60, 0xe9, 0xc6, 0x6a, 0x47, 0xcf, 0xa1, 0x9a,
	0x66, 0x9b, 0x56, 0xc3, 0x1a, 0x9a, 0x53, 0x55, 0xac, 0x00, 0x9a, 0x8a, 0xf7, 0x5a, 0x87, 0x25,
	0x0d, 0xad, 0xc2, 0x93, 0x29, 0x7f, 0x7f, 0xd0, 0xea, 0x95, 0x32, 0xe8, 0x03, 0x58, 0x9e, 0x0a,
	0x34, 0xbb, 0x7d, 0xb3, 0xb5, 0x5b, 0xca, 0x6e, 0xfc, 0x9e, 0x3c, 0x7f, 0xba, 0x7d, 0xd1, 0x47,
	0xb0, 0x96, 0xa6, 0x36, 0x9a, 0xcd, 0x96, 0x69, 0xda, 0xdd, 0xd6, 0x41, 0xab, 0x3b, 0x55, 0xc1,
	0x5d, 0x59, 0xed, 0x61, 0xb7, 0xab, 0x3c, 0x25, 0x0d, 0xd5, 0xe0, 0xf9, 0x7b, 0xb3, 0x8c, 0x56,
	0x63, 0xd7, 0xee, 0xf7, 0xba, 0xaf, 0x4b, 0x99, 0x3b, 0x73, 0x7a, 0xfd, 0x94, 0x93, 0xad, 0xff,
	0x99, 0x83, 0x42, 0xfc, 0xc5, 0x72, 0x93, 0x84, 0x17, 0xd4, 0x21, 0xe8, 0x27, 0x0d, 0xf2, 0xd7,
	0x6e, 0x07, 0xe8, 0x8b, 0x19, 0x3f, 0xa7, 0xdb, 0xf7, 0x8c, 0xea, 0x97, 0x0f, 0x91, 0xaa, 0x61,
	0xfe, 0x4d, 0x93, 0x97, 0x94, 0xe9, 0x3f, 0x1b, 0xd4, 0x98, 0x9d, 0x79, 0xc7, 0xdf, 0x5c, 0x75,
	0xe7, 0xbf, 0x20, 0x54, 0x79, 0xbf, 0x68, 0xb0, 0x74, 0x63, 0xd7, 0xa1, 0xed, 0xd9, 0xa9, 0xb7,
	0x56, 0x67, 0xf5, 0xab, 0x87, 0x89, 0x55, 0x31, 0xdf, 0xc3, 0x82, 0xda, 0x05, 0xe8, 0xe5, 0xec,
	0xa0, 0x6b, 0xeb, 0xa4, 0xfa, 0xf9, 0x7d, 0x65, 0xc9, 0xc9, 0x3b, 0x18, 0x9e, 0x85, 0xd1, 0x95,
	0x96, 0x4e, 0xe5, 0x0f, 0xb4, 0x37, 0x05, 0x7d, 0x73, 0x3b, 0x81, 0xe1, 0x80, 0xbe, 0xcb, 0xcc,
	0x59, 0x9d, 0xc6, 0xa0, 0xf3, 0x47, 0xa6, 0x6c, 0x29, 0x4d, 0x47, 0xc6, 0x1a, 0x01, 0xd5, 0x0f,
	0xb6, 0xfe, 0xce, 0xfc, 0x5f, 0xb9, 0x8f, 0x12, 0xf7, 0xd1, 0xc1, 0xd6, 0xf1, 0xbc, 0xbc, 0x29,
	0x7d, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0xe9, 0xe8, 0xb9, 0x2e, 0x0b, 0x00, 0x00,
}
