version: "3"

services:
  trade_bot:
    build:
      dockerfile: cmd/trade-bot/Dockerfile
      context: .
    container_name: trade_bot
    env_file:
      - cmd/trade-bot/.env
    restart_policy:
      condition: on-failure
      max-attempts: 3
    networks:
      - bot_internal

  grafana:
    image: grafana/grafana:8.2.6-ubuntu
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - default
      - bot_internal

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - default
      - bot_internal


volumes:
  grafana_data:
  prometheus_data:


networks:
  default:
  bot_internal:
    internal: true
