version: "3"

services:
  trade_bot:
    build:
      dockerfile: cmd/trade-bot/Dockerfile
      context: .
    env_file:
      - cmd/trade-bot/.env
    restart_policy:
      condition: on-failure
      max-attempts: 3
