version: "3"

services:
  trade_bot:
    build:
      dockerfile: cmd/trade-bot/Dockerfile
      context: .
    env_file:
      - cmd/trade-bot/.env
    restart: "always"

  grafana:
    image: grafana/grafana:8.2.6-ubuntu
    container_name: grafana
    hostname: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    network_mode: 'host'


volumes:
  grafana_data:
  prometheus_data:
