{
 "title": "TradeBot",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": {
     "query": "label_values(tradebot_portfolio_instruments_amount, account_id)"
    }
   },
   {
    "name": "bot_id",
    "query": {
     "query": "label_values(tradebot_api_requests, bot_id)"
    }
   },
   {
    "name": "figi",
    "query": {
     "query": "label_values(tradebot_orders_placed{bot_id=~\"$bot_id\"}, figi)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(tradebot_api_requests, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running trading bots",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(tradebot_info) by (bot_id, sdk_version, selected_strategy, workers)"
    }
   ]
  },
  { "title": "Trade Bot Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Stop loss decisions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "tradebot_stop_loss_decisions{bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}} (bot-{{bot_id}})"
    }
   ]
  },
  {
   "title": "Take profit desicions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "tradebot_take_profit_decisions{bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}} (bot-{{bot_id}})"
    }
   ]
  },
  {
   "title": "Instruments purchased",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "tradebot_instruments_purchased{bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}} (bot-{{bot_id}})"
    }
   ]
  },
  {
   "title": "BUY orders placed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "tradebot_orders_placed{direction=\"ORDER_DIRECTION_BUY\",bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}} (bot-{{bot_id}})"
    }
   ]
  },
  {
   "title": "Orders fulfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "tradebot_orders_fulfilled{bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{direction}}: {{figi}}"
    }
   ]
  },
  {
   "title": "SELL orders placed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "tradebot_orders_placed{direction=\"ORDER_DIRECTION_SELL\",bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}} (bot-{{bot_id}})"
    }
   ]
  },
  {
   "title": "Unhealthy workers killed",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tradebot_stopped_by_circuit_breaker{bot_id=~\"$bot_id\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}} (bot-{{bot_id}})"
    }
   ]
  },
  { "title": "Tinkoff Invest API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "API call errors",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tradebot_api_call_errors{bot_id=~\"$bot_id\",service=~\"$service\"}[$__range]) ",
     "legendFormat": "(bot-{{bot_id}}) [{{service}}] {{method}}: {{error}}"
    }
   ]
  },
  {
   "title": "$service API rpm",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "repeat": "service",
   "targets": [
    {
     "expr": "rate(tradebot_api_requests{bot_id=~\"$bot_id\",service=~\"$service\"}[1m]) * 60",
     "legendFormat": "{{method}} (bot-{{bot_id}})"
    }
   ]
  },
  { "title": "Trade Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }, "repeat": "account_id" },
  {
   "title": "Portfolio instruments amount ($account_id)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "tradebot_portfolio_instruments_amount{account_id=~\"$account_id\"} != 0",
     "legendFormat": "{{instrument}} ({{currency}})"
    }
   ]
  },
  {
   "title": "Portfolio expected yield ($account_id)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "tradebot_portfolio_expected_yield_overall{account_id=~\"$account_id\"} != 0",
     "legendFormat": "{{account_id}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Normal trading status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "tradebot_instrument_trading_status{status=\"SECURITY_TRADING_STATUS_NORMAL_TRADING\",figi=~\"$figi\"}",
     "legendFormat": "{{figi}}"
    }
   ]
  }
 ]
}