name: CI

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'cmd/**'
      - 'internal/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  build-trade-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - run: go build -a -o trade-bot ./cmd/trade-bot
      
  build-trade-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - run: go build -a -o trade-utils ./cmd/trade-utils
